using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace Entities
{
    public class Archive
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "تصویر کالا")]
        public string? ImageName { get; set; }
        [Display(Name = "تصویر محصول")]
        [NotMapped]
        public IFormFile ImageFile { get; set; }

        /// <summary>
        /// automatic generated by sql engeen
        /// </summary>
        [Display(Name = "تاریخ بارگذاری")]
        public string? DateTimeCreated { get; set; }
        [Display(Name = "کالا")]
        public int ProductId { get; set; }
        [ForeignKey("ProductId")]
        public virtual Product? product { get; set; }
    }
}
